Make Nextflow parser compatible v1/v2 + path resolution changed, now located relative to the directory where launch Nextflow

diff --git a/.github/workflows/nf-test.yml b/.github/workflows/nf-test.yml
--- a/.github/workflows/nf-test.yml
+++ b/.github/workflows/nf-test.yml
@@ -58,7 +58,7 @@ jobs:
           echo ${{ steps.set-shards.outputs.total_shards }}
 
   nf-test:
-    name: "${{ matrix.profile }} | ${{ matrix.NXF_VER }} | ${{ matrix.shard }}/${{ needs.nf-test-changes.outputs.total_shards }}"
+    name: "${{ matrix.profile }} | ${{ matrix.NXF_VER }} | parser ${{ matrix.NXF_PARSER }} | ${{ matrix.shard }}/${{ needs.nf-test-changes.outputs.total_shards }}"
     needs: [nf-test-changes]
     if: ${{ needs.nf-test-changes.outputs.total_shards != '0' }}
     runs-on: # use self-hosted runners
@@ -77,11 +77,17 @@ jobs:
             profile: "conda"
           - isMain: false
             profile: "singularity"
+          - NXF_VER: "24.10.0"
+            NXF_PARSER: "v2"
         NXF_VER:
           - "24.10.0"
-          - "latest-everything"
+          - "26.04.6"
+        NXF_PARSER:
+          - "v1"
+          - "v2"
     env:
       NXF_ANSI_LOG: false
+      NXF_SYNTAX_PARSER: ${{ matrix.NXF_PARSER }}
       TOTAL_SHARDS: ${{ needs.nf-test-changes.outputs.total_shards }}
 
     steps:
@@ -92,7 +98,6 @@ jobs:
       - name: Run nf-test
         id: run_nf_test
         uses: ./.github/actions/nf-test
-        continue-on-error: ${{ matrix.NXF_VER == 'latest-everything' }}
         env:
           NFT_WORKDIR: ${{ env.NFT_WORKDIR }}
           NXF_VERSION: ${{ matrix.NXF_VER }}
@@ -105,15 +110,10 @@ jobs:
         if: ${{ always() }}
         run: |
           if [[ "${{ steps.run_nf_test.outcome }}" == "failure" ]]; then
-            echo "::error::Test with ${{ matrix.NXF_VER }} failed"
+            echo "::error::Test with ${{ matrix.NXF_VER }} and parser ${{ matrix.NXF_PARSER }} failed"
             # Add to workflow summary
-            echo "## ❌ Test failed: ${{ matrix.profile }} | ${{ matrix.NXF_VER }} | Shard ${{ matrix.shard }}/${{ env.TOTAL_SHARDS }}" >> $GITHUB_STEP_SUMMARY
-            if [[ "${{ matrix.NXF_VER }}" == "latest-everything" ]]; then
-              echo "::warning::Test with latest-everything failed but will not cause workflow failure. Please check if the error is expected or if it needs fixing."
-            fi
-            if [[ "${{ matrix.NXF_VER }}" != "latest-everything" ]]; then
-              exit 1
-            fi
+            echo "## ❌ Test failed: ${{ matrix.profile }} | ${{ matrix.NXF_VER }} | parser ${{ matrix.NXF_PARSER }} | Shard ${{ matrix.shard }}/${{ env.TOTAL_SHARDS }}" >> $GITHUB_STEP_SUMMARY
+            exit 1
           fi
 
   confirm-pass:
